services:
  watch-my-git:
    # Uncomment the line below to build the Dockerfile locally
    # build: .

    image: ghcr.io/0xn1nja/watch-my-git:latest
    container_name: watch-my-git
    restart: unless-stopped

    volumes:
      - ./data:/app/data

    env_file:
      - .env

    environment:
      - FOLLOWERS_DB_PATH=/app/data/followers.db
